version: '3.5'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: 'postgres_test'
      POSTGRES_PASSWORD: 'postgres_test'
      POSTGRES_DB: 'postgres_test'
    ports:
      - '5433:5432'
